[tool.black]
line-length = 99
target-version = ["py38"]

[tool.isort]
profile = "black"
line_length = 99

[tool.ruff]
line-length = 99
select = ["E9", "F401", "F7", "F82"]
show-source = true
target-version = "py38"