[tool.black]
line-length = 99
target-version = ["py39"]

[tool.isort]
profile = "black"
line_length = 99

[tool.ruff]
line-length = 99
lint.select = ["E9", "F401", "F7", "F82"]
output-format = "full"
target-version = "py39"
