blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://discord.gg/GET4DVk
    about: "Join the Cog Support Server for questions or support, Ping K u r o#2740 in #support_othercogs!"