blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://discord.gg/GET4DVk
    about: "Join the Cog Support Server for questions or support, and find my thread (Kuro-Cogs) in #support-othercogs!"