name: Feature Request
description: Submit a feature request for one of the cogs.
labels: [enhancement]
assignees: "Kuro-Rui"
body:
  - type: dropdown
    id: cog
    attributes:
      label: Cog
      description: Which cog are you proposing a feature request for?
      options:
        - AvatarImgen
        - BotPing
        - CounterCog
        - FakeMod
        - Fumo
        - Hack
        - ImgBB
        - Osu
        - Polls
        - ReactLog
        - ReactTermino
        - Sudo
    validations:
      required: true
  - type: input
    id: details
    attributes:
      label: Details
      description: "Describe your request:"
    validations:
      required: true