name: Others
description: Submit an issue that doesn't belong to other categories.
labels: [others]
assignees: "Kuro-Rui"
body:
  - type: input
    id: details
    attributes:
      label: Issue Details
      description: Please provide details about the issue.
    validations:
      required: true