name: Lint Python

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.ref }}
      - name: Set Up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Flake8
        run: python -m pip install flake8
      - name: Flake8 Linting
        run: python -m flake8 . --count --select=E9,F7,F82 --show-source