name: Tox
on:
  push:
  pull_request:

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - "3.8"
          - "3.9"
        tox_env:
          - pytest
        include:
          - tox_env: pytest
            friendly_name: Tests

      fail-fast: false

    name: Python ${{ matrix.python_version }} - ${{ matrix.friendly_name }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.ref }}
      - name: Set Up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Cache Tox
        uses: actions/cache@v2
        with:
          path: .tox
          key: tox-${{ matrix.python_version }}-${{ matrix.tox_env }}-${{ hashFiles('tox.ini') }}
      - name: Install Tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: "Run Tox: ${{ matrix.friendly_name }}"
        env:
          TOXENV: ${{ matrix.tox_env }}
        run: |
          tox